application: strathclydepgrs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(ico|gif|png|jpg|js|css|html))
  static_files: \1
  upload: (.*\.(ico|gif|png|jpg|js|css|html))

- url: /sitemap.xml.gz
  static_files: sitemap.xml.gz
  upload: sitemap.xml.gz
